export const venueTypes = [
  { id: 1, name: "4 Star & Above Wedding Hotels" },
  { id: 2, name: "Banquet Halls" },
  { id: 3, name: "Lawns / Farmhouses" },
  { id: 4, name: "3 Star Hotels with Banquets" },
  { id: 5, name: "Country / Golf Club" },
  { id: 6, name: "Wedding Resorts" },
  { id: 7, name: "Party Restaurants / Lounge Bars" },
  { id: 8, name: "Forts / Palaces For Wedding" },
  { id: 9, name: "Destination Wedding" },
  { id: 10, name: "Kalyana Mandapams" },
  { id: 11, name: "Small Function / Party Halls" },
  { id: 12, name: "Venues With Rooms" },
  { id: 13, name: "5 Star Luxury Wedding Hotels" },
  { id: 14, name: "Temple Wedding Venues" },
]

export const Cuisine_Types = [
  { id: 1, name: 'Italian' },
  { id: 2, name: 'Mexican' },
  { id: 3, name: 'Indian' },
  { id: 4, name: 'Chinese' },
  { id: 5, name: 'Japanese' },
  { id: 6, name: 'Thai' },
  { id: 7, name: 'Mediterranean' },
  { id: 8, name: 'French' },
  { id: 9, name: 'Greek' },
  { id: 10, name: 'Spanish' },
  { id: 11, name: 'Middle Eastern' },
  { id: 12, name: 'American' },
  { id: 13, name: 'British' },
  { id: 14, name: 'German' },
  { id: 15, name: 'Vietnamese' },
  { id: 16, name: 'Korean' },
  { id: 17, name: 'Brazilian' },
  { id: 18, name: 'Caribbean' },
  { id: 19, name: 'African' },
  { id: 20, name: 'Russian' },
  { id: 21, name: 'Turkish' },
  { id: 22, name: 'Australian' },
  { id: 23, name: 'Cajun' },
  { id: 24, name: 'Irish' },
  { id: 25, name: 'Swiss' },
  { id: 26, name: 'Scandinavian' },
  { id: 27, name: 'Peruvian' },
  { id: 28, name: 'Argentinian' },
  { id: 29, name: 'Portuguese' },
  { id: 30, name: 'Continental'}
];

export const Facility_Types = [
  { id: 1, name: 'Parking' },
  { id: 2, name: 'Wi-Fi' },
  { id: 3, name: 'Projector' },
  { id: 4, name: 'Catering' },
  { id: 5, name: 'Air Conditioning' },
  { id: 6, name: 'Stage' },
  { id: 7, name: 'Sound System' },
  { id: 8, name: 'Lighting System' },
  { id: 9, name: 'Dance Floor' },
  { id: 10, name: 'Decorations' },
  { id: 11, name: 'Wheelchair Accessible' },
  { id: 12, name: 'Bar Service' },
  { id: 13, name: 'Security Personnel' },
  { id: 14, name: 'Valet Parking' },
  { id: 15, name: 'Bridal Suite' },
  { id: 16, name: "Groom's Room" },
  { id: 17, name: 'Swimming Pool' },
  { id: 18, name: 'Fitness Center' },
  { id: 19, name: 'Spa Services' },
  { id: 20, name: 'Shuttle Service' }
];
